docs: add how to set up cluster info from webpage to our repo
catenax-ng/cloud-infra pull request #14
Opened 2024-02-07 16:11 UTC by FaGru3n

#### What would be changed or will be added with this PR?
- move and adapt format for Markdown files for our internal guides to onboarding tasks
- last remaining `docs/how-to-setup-aks-cluster-via-terraform.md`  from catena-x ng website
- remove specific docusaurus content and tranfer it to Markdown format like https://docusaurus.io/docs/next/markdown-features/admonitions

#### Why do i want to change this?
- reason https://github.com/eclipse-tractusx/sig-infra/issues/348 reduce content on webpage

#### Validation
- check the new files and its base content on our webpage https://catenax-ng.github.io/docs/internal/how-to-setup-aks-cluster-via-terraform

2024-02-08 05:20 UTC, SebastianBezold requested changes
Just the part about the state should be updated. Rest is fine

2024-02-08 05:20 UTC, SebastianBezold commented on docs/how-to-setup-aks-cluster-via-terraform.md
> +terraform state to track our AKS cluster resources. We think, that sharing and storing the state file is too much of an
This is definitely outdated and we should point to the backend configuration in the terraform scripts

2024-02-09 10:15 UTC, FaGru3n commented on docs/how-to-setup-aks-cluster-via-terraform.md
> +terraform state to track our AKS cluster resources. We think, that sharing and storing the state file is too much of an
[22e0f6c](https://github.com/catenax-ng/cloud-infra/pull/14/commits/22e0f6c489ea4f8c5e8cd3311b541296a5085708)

Did some changes, where directly you want to point to the scripts?

2024-02-16 09:55 UTC, SebastianBezold commented on docs/how-to-setup-aks-cluster-via-terraform.md
> +terraform state to track our AKS cluster resources. We think, that sharing and storing the state file is too much of an
This is where it is defined for the core cluster for example: https://github.com/catenax-ng/cloud-infra/blob/main/01_core_cluster/providers.tf#L2

2024-02-16 09:56 UTC, SebastianBezold commented on docs/how-to-setup-aks-cluster-via-terraform.md
> +terraform state to track our AKS cluster resources. We think, that sharing and storing the state file is too much of an
But fine for now. At least the outdated parts are removed. We can improve the docs with up-to-date stuff later on

2024-02-16 09:56 UTC, SebastianBezold approved these changes

2024-02-16 10:20 UTC, merged